export const SITE_CONFIG = {
  name: "YallaCode",
  tagline: "Next-Gen Software & AI Solutions",
  url: "https://yallacode.tech",
  email: "hello@yallacode.tech",
  phone: "",
  location: "Global — Remote First",
  description:
    "YallaCode is a full-stack software development and AI agency that builds scalable web apps, mobile apps, cloud infrastructure, and intelligent automation systems for startups and enterprises.",
  keywords: [
    "software company",
    "AI agency",
    "web development",
    "mobile app development",
    "full-stack development",
    "cloud architecture",
    "machine learning",
    "artificial intelligence",
    "SaaS development",
    "custom software",
    "startup software",
    "enterprise software",
    "DevOps",
    "UI UX design",
    "API development",
    "microservices",
    "automation",
    "intelligent systems",
    "YallaCode",
    "software development company",
    "AI solutions",
    "digital transformation",
    "fintech software",
    "healthcare AI",
    "edtech platforms",
    "e-commerce development",
    "React development",
    "Next.js development",
    "Node.js development",
    "Python development",
    "AI consulting",
  ] as string[],
  social: {
    linkedin: "https://linkedin.com/company/yallacode",
    twitter: "https://twitter.com/yallacode",
    github: "https://github.com/yallacode",
    instagram: "https://instagram.com/yallacode",
    facebook: "https://facebook.com/yallacode",
    youtube: "https://youtube.com/@yallacode",
  },
} as const;
